### ISSUE TITLE
Plugin doesn’t work

### ISSUE THREAD

**Issue by xazac** [jubepue/homebridge-petkit-platform#1]
Hi there,

the plugin doesn’t work:

`20/2/2023, 22:18:35Petkit Platform BridgeLoaded plugin 'homebridge-petkit-platform'
20/2/2023, 22:18:35Petkit Platform BridgeLoading 1 platforms...
20/2/2023, 22:18:35Petkit Platform BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'debug')
20/2/2023, 22:19:15Petkit Platform BridgeRegistering platform 'homebridge-petkit-platform.PetkitPlatform'
20/2/2023, 22:19:15W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
20/2/2023, 22:19:15W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
20/2/2023, 22:19:15W: Some index files failed to download. They have been ignored, or old ones used instead.
20/2/2023, 22:20:40Petkit Platform BridgeConfiguration change
20/2/2023, 22:20:40petkitplatformbridge stopping `

Can you please specify manual configuration?
I can’t find country code and/or any other parameter.

Thanks

**Comment by jubepue** [comment]
Hi,I'm on it. For the moment, while I create the manual, you can put debug: true or false and the country code (Spain is 34, Germany 49) matches the telephone country codeEl 20 feb 2023, a las 22:37, xazac ***@***.***> escribió:﻿
Hi there,
the plugin doesn’t work:
20/2/2023, 22:18:35Petkit Platform BridgeLoaded plugin 'homebridge-petkit-platform' 20/2/2023, 22:18:35Petkit Platform BridgeLoading 1 platforms... 20/2/2023, 22:18:35Petkit Platform BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'debug') 20/2/2023, 22:19:15Petkit Platform BridgeRegistering platform 'homebridge-petkit-platform.PetkitPlatform' 20/2/2023, 22:19:15W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging ***@***.***> 20/2/2023, 22:19:15W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging ***@***.***> 20/2/2023, 22:19:15W: Some index files failed to download. They have been ignored, or old ones used instead. 20/2/2023, 22:20:40Petkit Platform BridgeConfiguration change 20/2/2023, 22:20:40petkitplatformbridge stopping 
Can you please specify manual configuration?
I can’t find country code and/or any other parameter.
Thanks

**Comment by xazac** [comment]
> Hi, I'm on it. For the moment, while I create the manual, you can put debug: true or false and the country code (Spain is 34, Germany 49) matches the telephone country code. jubepue

Well, it still doesn't work at all:

`2/2/2023, 11:35:14Petkit Platform Bridge starting
22/2/2023, 11:35:25Petkit Platform BridgeLoaded plugin 'homebridge-petkit-platform'
22/2/2023, 11:35:25Petkit Platform BridgeLoading 1 platforms...
22/2/2023, 11:35:25Petkit Platform BridgePetkitPlatformThe config configuration is incorrect, disabling plugin.
22/2/2023, 11:35:25Petkit Platform BridgeBridge is running on port 51836.`

**Comment by jubepue** [comment]
Hi,
You must to put “,”
   
       {
            "options": {
                "username": "xxxxx",
                "password": "xxxxx",
                "lang": "en",
                "countryCode": 39,
                "debug": false
            },
            "name": "PetkitPlatform",
            "platform": "PetkitPlatform"
        },

**Comment by xazac** [comment]
This is the Bridge configuration:

![DF8BC058-814C-46D3-8379-D5ECA78C6F7E](https://user-images.githubusercontent.com/10470552/220715322-5eaf9f6a-38f2-447d-87ba-961482b7b458.jpeg)

**Comment by jubepue** [comment]
Hi,
Please, delete plugin and ita config and reinstall it

**Comment by nicoodeimos** [comment]
Having the same issue.
configuration is incorrect by default.

**Comment by jubepue** [comment]
Hi,
The last release is ok!
Close.
