### ISSUE TITLE
No support for Fresh Element Gemini

### ISSUE THREAD

**Issue by rgreco87** [jubepue/homebridge-petkit-platform#3]
I installed plugin v1.0.6, bridge is running but no accessory is found.

Can you please add Fresh Element Gemini support?
Thanks

**Comment by jubepue** [comment]
Hi,
What is the model tupe? (fresh element SOLO is D4) you can find out by putting the plugin in debug mode, and see it in "type" in the logs

**Comment by rgreco87** [comment]
> Hi,
> What is the model tupe? (fresh element SOLO is D4) you can find out by putting the plugin in debug mode, and see it in "type" in the logs

Hi there, I can't find what you asked in debug logs.
That's my model: https://petkit.com/products/fresh-element-gemini

I found this on Amazon product page: **Item model number: ‎ P590**
https://www.amazon.com/PETKIT-Hoppers-Automatic-Dispenser-Capacity/dp/B0BF56RTQH?th=1

**Comment by rgreco87** [comment]
27/2/2023, 20:24:53Petkit Platform BridgeAdding: Freshelement Gemini (D4s / 10000364)

**Comment by jubepue** [comment]
Hi,
You can install the new release.
